### ISSUE TITLE
Random selection is not random

### ISSUE THREAD

**Issue by dougsisco** [NautiluX/slide#28] opened 2021-02-03 03:12 UTC
The random selection selection of photos is not random: I have about 25 photos and after viewing the 'random' selections for about five minutes I found that the same few photos were shown 90% of the time.  

You need to change the 'random' selector so that it does not choose the previously shown images until all of the others have been shown, something like dealing a deck of cards.  

There also may be something wrong with your random selector: I see that ImageSelector::updateImage() uses the image's size() to help select the image- unsigned int selectedImage = rand() % images.size(); 
I believe this is a bug.

The current selection scheme makes the program almost worthless. I would fix it myself but your program also does not have a fade transition which is a feature that I really want for my photo frame.

**Comment by NautiluX** [comment] 2021-02-10 14:45
Hi @dougsisco glad your trying this tool! It has a shuffle mode which you can start with `-s` to make sure all your images are viewed once before starting over. Fade transition could be possible to implement, I just didn't have the use-case for it, PR welcome :)

**Comment by mikey4321** [comment] 2021-03-03 18:01
i can't comment on the code specifics, but i have had the same issue as @dougsisco.  

Random mode on a large folder of photos seems to end up just repeating a limited portion of them, whereas shuffle seems to show a much wider selection which i think is all of them.  Might be worth removing random and just having shuffle as the  option.

**Comment by magica237** [comment] 2021-03-03 19:07
I have noticed this in previous version of a program (0.9.0). As I don´t turn off the screen but whole Raspi at night and after new start different selection of pictures was shown, I have considered it a feature, not a bug :)

**Comment by NautiluX** [comment] 2021-03-04 15:25
Fading transition added in releas [0.9.10](https://github.com/NautiluX/slide/releases/tag/v0.9.10), shuffle mode should fix your randomization issue. Closing this issue.

**Closed by NautiluX** 2021-03-04 15:25 UTC
